PermitRootLogin no
PermitEmptyPasswords no
MaxAuthTries 6

PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication yes
ChallengeResponseAuthentication yes

UsePAM yes
AuthenticationMethods publickey publickey,keyboard-interactive

UseDNS no
