PermitRootLogin no
PermitEmptyPasswords no
MaxAuthTries 6
ChallengeResponseAuthentication yes
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication yes
UseDNS no
UsePAM yes
AuthenticationMethods publickey,password publickey,keyboard-interactive
