unbind r
bind r source-file ~/.tmux.conf

if-shell 'test -d /data/data/com.termux' {
    set -g default-shell /data/data/com.termux/files/usr/bin/zsh
} {
    set -g default-shell /usr/bin/zsh
}
set -g default-terminal "tmux-256color"
set -g xterm-keys on
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g set-clipboard on
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g detach-on-destroy off
set -s escape-time 0
set-option -g focus-events on
set-option -g display-time 4000
setw -g mode-keys vi

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind-key -n C-S-Left swap-window -d -t -1
bind-key -n C-S-Right swap-window -d -t +1

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'maxpetretta/tmux-monokai-pro'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @monokai-show-powerline true
set -g @monokai-show-flags true
set -g @monokai-show-left-icon session
set -g status-position bottom
set -g lock-command "vlock"

run '~/.tmux/plugins/tpm/tpm'
